=== FatBouk/NRT_15_19/oglasiV.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Oglasi" type="w3s:OglasiType" xmlns:w3s="https://www.w3schools.com" />
    <xs:complexType name="DatumType">
        <xs:sequence>
            <xs:element name="Dan">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minExclusive value="0"></xs:minExclusive>
                        <xs:maxInclusive value="31"></xs:maxInclusive>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Mesec">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minExclusive value="0"></xs:minExclusive>
                        <xs:maxInclusive value="12"></xs:maxInclusive>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:int" name="Godina" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="restrictionCena">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"></xs:minExclusive>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="CenaType">
        <xs:simpleContent>
            <xs:extension base="w3s:restrictionCena" xmlns:w3s="https://www.w3schools.com">
                <xs:attribute name="valuta" use="optional" default="rsd">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="eur"></xs:enumeration>
                            <xs:enumeration value="rsd"></xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TagoviType">
        <xs:sequence>
            <xs:element type="xs:string" name="Tag" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="emailType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="tip" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="kontaktType">
        <xs:sequence>
            <xs:element type="w3s:emailType" name="email" maxOccurs="unbounded" minOccurs="0" xmlns:w3s="https://www.w3schools.com" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OglasType">
        <xs:sequence>
            <xs:element type="xs:string" name="Kategorija" />
            <xs:element type="w3s:DatumType" name="Datum" xmlns:w3s="https://www.w3schools.com" />
            <xs:element type="w3s:CenaType" name="Cena" xmlns:w3s="https://www.w3schools.com" />
            <xs:element type="xs:string" name="Tekst" />
            <xs:element type="w3s:TagoviType" name="Tagovi" xmlns:w3s="https://www.w3schools.com" />
            <xs:element type="w3s:kontaktType" name="kontakt" xmlns:w3s="https://www.w3schools.com" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OglasiType">
        <xs:sequence>
            <xs:element type="w3s:OglasType" name="Oglas" maxOccurs="unbounded" minOccurs="0" xmlns:w3s="https://www.w3schools.com" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== FatBouk/NRT_15_19/oglasi.xml
<?xml version="1.0"?>
<Oglasi xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com oglasiV.xsd">
    <Oglas>
        <Kategorija>Automobil</Kategorija>
        <Datum>
            <Dan>6</Dan>
            <Mesec>8</Mesec>
            <Godina>2022</Godina>
        </Datum>
        <Cena valuta="eur">2000</Cena>
        <Tekst>Tekst oglasa</Tekst>
        <Tagovi>
            <Tag>1992</Tag>
            <Tag>Benzin</Tag>
        </Tagovi>
        <kontakt>
            <email tip="privatni">bogdan@gmail.com</email>
            <email tip="sluzbeni">bogdannrt1519@gs.viser.edu.rs</email>
        </kontakt>
    </Oglas>
    <Oglas>
        <Kategorija>Stan</Kategorija>
        <Datum>
            <Dan>2</Dan>
            <Mesec>5</Mesec>
            <Godina>2021</Godina>
        </Datum>
        <Cena valuta="eur">50000</Cena>
        <Tekst>Stan u beogradu</Tekst>
        <Tagovi>
            <Tag>100m2</Tag>
            <Tag>Vozdovac</Tag>
        </Tagovi>
        <kontakt>
            <email tip="privatni">petar@gmail.com</email>
        </kontakt>
    </Oglas>
</Oglasi>
